### ISSUE TITLE
出个使用教程吧

### ISSUE THREAD

**Issue by zdeicn** [Superheroff/douyin_uplod#1]
出个使用教程吧

**Comment by Superheroff** [comment]
> 出个使用教程吧

如何运行里面有告诉你怎么运行
第一次使用需要先运行get_cookie.py，会生成一个cookie_手机号.json的文件，把它修改成cookie.json，再运行main.py

**Comment by wss-git** [comment]
> > 出个使用教程吧
> 
> 如何运行里面有告诉你怎么运行 第一次使用需要先运行get_cookie.py，会生成一个cookie_手机号.json的文件，把它修改成cookie.json，再运行main.py

![image](https://github.com/Superheroff/douyin_uplod/assets/56686088/5fef6ee1-080c-404e-b8e9-0ffcce8919b3)
这里貌似存在问题

**Comment by wss-git** [comment]
![image](https://github.com/Superheroff/douyin_uplod/assets/56686088/b15a3665-d2d8-41f2-a2b2-446b1ee1f30b)
这样貌似可以运行了
