### ISSUE TITLE
请问有Playwright 的程序，能运行在一个没有装过图形界面的 linux vps上吗？

### ISSUE THREAD

**Issue by bk111** [Superheroff/douyin_uplod#11]
1. 请问有Playwright 的程序(不牵扯 cookie)，能运行在一个没有装过图形界面的 linux vps上吗？
2. 有Playwright 的程序(有windows下chrome的 cookie)，能运行在一个没有装过图形界面的 linux vps上吗？

**Comment by Superheroff** [comment]
> 1. 请问有Playwright 的程序(不牵扯 cookie)，能运行在一个没有装过图形界面的 linux vps上吗？
> 
> 2. 有Playwright 的程序(有windows下chrome的 cookie)，能运行在一个没有装过图形界面的 linux vps上吗？

Playwright支持在Windows和Linux上使用
