### ISSUE TITLE
请给出 get_cookie.py 执行后正常的示例文件。我执行get_cookie.py并照提示输入手机号填入验证码但不行。我想按你的最终cookie文件自行走这一步

### ISSUE THREAD

**Issue by bk111** [Superheroff/douyin_uplod#12]
请给出 get_cookie.py 执行后正常的一个示例文件(包括文件名格式. 是netscape兼容格式吗?)。我执行get_cookie.py并照提示输入手机号填入验证码但不行。我想按你的最终cookie文件自行抓cookie试一下。

**Comment by Superheroff** [comment]
> 请给出 get_cookie.py 执行后正常的一个示例文件(包括文件名格式. 是netscape兼容格式吗?)。我执行get_cookie.py并照提示输入手机号填入验证码但不行。我想按你的最终cookie文件自行抓cookie试一下。

下次更新我写个dockerfile吧
