### ISSUE TITLE
自动化脚本测试建议

### ISSUE THREAD

**Issue by Absolute-2ero** [Superheroff/douyin_uplod#14]
大佬可否给一个headless=True的脚本？或者说自动化运行模式下该点击哪个元素去获取验证码呢

**Comment by kebenxiaoming** [comment]
你自己改也很简单，在代码里搜索headless，然后将所有headless=True改为headless=False即可哈

**Comment by Superheroff** [comment]
> 大佬可否给一个headless=True的脚本？或者说自动化运行模式下该点击哪个元素去获取验证码呢

不支持无头模式
