### ISSUE TITLE
发布视频报错，似乎是定位不到上传视频的组件

### ISSUE THREAD

**Issue by polo2013** [Superheroff/douyin_uplod#17]
mac
前面都ok
发布视频，error。如下：
![WX20240918-163007@2x](https://github.com/user-attachments/assets/3cff826d-bc97-45d7-810e-c22f07ae388a)
感觉应该是这一步没有定位到上传的组件，但是看写法又好像没什么问题。

**Comment by withwz** [comment]
不需要打开文件选择器，这步多余，直接往input中塞就行，await page.set_input_files("input[type='file']"

看这个https://github.com/withwz/douyin_upload/blob/b485b91a34a602edfb7a98a8ce317867c82886af/main.py#L60
