### ISSUE TITLE
音乐榜单获取失败，怎么回事

### ISSUE THREAD

**Issue by laotang8** [Superheroff/douyin_uplod#5]
音乐榜单获取失败，怎么回事
<img width="714" alt="60c0c371695cc226b9214d8aaeaad20" src="https://github.com/Superheroff/douyin_uplod/assets/81150204/4c29c19a-8674-40cd-a444-5b823a2a0754">

**Comment by Superheroff** [comment]
> 音乐榜单获取失败，怎么回事
> 
> <img width="714" alt="60c0c371695cc226b9214d8aaeaad20" src="https://github.com/Superheroff/douyin_uplod/assets/81150204/4c29c19a-8674-40cd-a444-5b823a2a0754">
> 
> 

看返回结果

**Comment by laotang8** [comment]
返回结果怎么看
