### ISSUE TITLE
配置文件怎么填写啊

### ISSUE THREAD

**Issue by laotang8** [Superheroff/douyin_uplod#6]
以下这一行怎么填写啊，是直接从抖音作者主页爬取视频，还是填写作者id就行，@作者，怎么@啊，有没有模板啊，@多个作者之间需要逗号，还是分号，格式是怎样的 <img width="536" alt="9a1413db9d388cf59ef3d1b42fd43ea" src="https://github.com/Superheroff/douyin_uplod/assets/81150204/95f621d7-b471-4caa-aaf9-991c262f3dc1">

**Comment by Superheroff** [comment]
填抖音号，不要加@和结尾空行

**Comment by laotang8** [comment]
<img width="485" alt="6ef3e4eef1cc6b4b51e8565db8f99e6" src="https://github.com/Superheroff/douyin_uplod/assets/81150204/f2264e4a-5505-4335-beb7-e7f46d52cddb">
这样吗？多个作者怎么怎么填写，有没有格式要求

**Comment by Superheroff** [comment]
> 
> 
> <img width="485" alt="6ef3e4eef1cc6b4b51e8565db8f99e6" src="https://github.com/Superheroff/douyin_uplod/assets/81150204/f2264e4a-5505-4335-beb7-e7f46d52cddb">
> 
> 这样吗？多个作者怎么怎么填写，有没有格式要求
> 
> 

列表格式啊
