### ISSUE TITLE
您好 麻烦问下 为什么我的视频放在video目录下 发布完成后视频内容不是我放在路径下的视频呢?

### ISSUE THREAD

**Issue by g707175425** [Superheroff/douyin_uplod#8]
您好 麻烦问下 为什么我的视频放在video目录下 发布完成后视频内容不是我放在路径下的视频呢 发布出去的视频好像是一个随机的视频 是我用法的问题吗?

**Comment by Superheroff** [comment]
> 您好 麻烦问下 为什么我的视频放在video目录下 发布完成后视频内容不是我放在路径下的视频呢 发布出去的视频好像是一个随机的视频 是我用法的问题吗?

自定义视频需要更改视频路径，你可以枚举video文件夹的所有视频，再把每个视频路径赋值给self.video_path
